# Generated by Django 2.2.15 on 2020-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_defined_id', models.IntegerField()),
                ('passenger_Cap', models.IntegerField()),
                ('fueltank_cap_liters', models.FloatField()),
                ('consumpt_per_minute_liters', models.FloatField()),
                ('max_minutes', models.CharField(max_length=100)),
            ],
        ),
    ]
