# Generated by Django 2.2.15 on 2020-08-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('model_name', models.CharField(max_length=200)),
                ('passenger_capacity', models.IntegerField()),
                ('fueltank_cap', models.FloatField()),
                ('consumption_per_minute', models.FloatField()),
                ('max_minutes', models.FloatField()),
            ],
        ),
    ]
