# Generated by Django 2.2.15 on 2020-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('za_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='max_minutes',
            field=models.TimeField(),
        ),
    ]
